spring.application.name=rent-service

spring.datasource.url=jdbc:postgresql://localhost:5432/rent_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

sigma.api.url=https://online.sigmasms.ru/api/sendings
sigma.api.token=859a4355599557d4cabceabcd37f6f740294abf5a5236aef2914890fda9cf5b5
sigma.sender=RentService
sigma.username=un4va1lablxx
sigma.password=jkLoop37!

app.sms.code-length=6
app.sms.code-ttl-seconds=300
app.sms.debug=true

file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

telegram.bot.token=8664272609:AAE_VxZt8-SZJu9iAP5-W7CfuSma20joVis
telegram.bot.username=RussiaRentBot

telegram.bot.proxy.host=127.0.0.1
telegram.bot.proxy.port=10808
telegram.bot.proxy.type=HTTP
